[package]
name = "crawler"
version = "0.1.0"
edition = "2024"

[dependencies]
libc = "0.2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
url = "2.5.4"
regex = "1.11.1"
texting_robots = "0.2.2"
roxmltree = "0.20"

[lib]
crate-type = ["cdylib"]
